-- GENERATED by engine/render.py from stack.yaml. Do not edit; edit stack.yaml.
{{ config(materialized='table') }}

-- Which customer segments carry which categories.
-- Grain: customer_segment, product_category

select
    d_customer.customer_segment                                                        as customer_segment,
    d_category.category_name                                                           as product_category,
    SUM(f.net_revenue)                                                                 as revenue,
    COUNT(DISTINCT f.order_id)                                                         as orders,
    CAST(SUM(f.net_revenue) / NULLIF(COUNT(DISTINCT f.order_id), 0) AS DECIMAL(18,2))  as avg_order_value,
    CAST(AVG(f.customer_rating) AS DECIMAL(3,2))                                       as avg_rating
from {{ ref('fct_orders') }} f
join {{ ref('dim_customer') }} d_customer on d_customer.customer_key = f.customer_key
join {{ ref('dim_category') }} d_category on d_category.category_key = f.category_key
group by 1, 2
order by revenue DESC
