-- GENERATED by engine/render.py from stack.yaml. Do not edit; edit stack.yaml.
{{ config(materialized='table') }}

-- Revenue and service quality per region.
-- Grain: region

select
    region                                                            as region,
    SUM(net_revenue)                                                  as revenue,
    COUNT(DISTINCT order_id)                                          as orders,
    SUM(quantity)                                                     as units,
    ROUND(SUM(net_revenue) / NULLIF(COUNT(DISTINCT order_id), 0), 2)  as avg_order_value,
    ROUND(AVG(discount) * 100, 2)                                     as avg_discount_pct,
    ROUND(AVG(customer_rating), 2)                                    as avg_rating,
    ROUND(AVG(delivery_days), 1)                                      as avg_delivery_days
from {{ ref('stg_sales_orders') }}
group by 1
order by revenue DESC
