-- GENERATED by engine/render.py from stack.yaml. Do not edit; edit stack.yaml.
{{ config(materialized='table') }}

-- Monthly revenue trend across the whole dataset.
-- Grain: order_month

select
    f.order_month                                                                      as order_month,
    SUM(f.net_revenue)                                                                 as revenue,
    SUM(f.gross_revenue)                                                               as gross_revenue,
    SUM(f.discount_amount)                                                             as discount_amount,
    COUNT(DISTINCT f.order_id)                                                         as orders,
    SUM(f.quantity)                                                                    as units,
    CAST(SUM(f.net_revenue) / NULLIF(COUNT(DISTINCT f.order_id), 0) AS DECIMAL(18,2))  as avg_order_value
from {{ ref('fct_orders') }} f
group by 1
order by order_month
