-- GENERATED by engine/render.py from stack.yaml. Do not edit; edit stack.yaml.
{{ config(materialized='table') }}

-- Revenue and margin-giveaway per product category.
-- Grain: product_category

select
    product_category                                                  as product_category,
    SUM(net_revenue)                                                  as revenue,
    SUM(gross_revenue)                                                as gross_revenue,
    SUM(discount_amount)                                              as discount_amount,
    COUNT(DISTINCT order_id)                                          as orders,
    SUM(quantity)                                                     as units,
    ROUND(SUM(net_revenue) / NULLIF(COUNT(DISTINCT order_id), 0), 2)  as avg_order_value,
    ROUND(AVG(discount) * 100, 2)                                     as avg_discount_pct,
    ROUND(AVG(customer_rating), 2)                                    as avg_rating
from {{ ref('stg_sales_orders') }}
group by 1
order by revenue DESC
