-- GENERATED by engine/render.py from stack.yaml. Do not edit; edit stack.yaml.
{{ config(materialized='table') }}

-- Category by region cross-tab — where each category actually sells.
-- Grain: product_category, region

select
    d_category.category_name                                                           as product_category,
    d_region.region_name                                                               as region,
    SUM(f.net_revenue)                                                                 as revenue,
    COUNT(DISTINCT f.order_id)                                                         as orders,
    SUM(f.quantity)                                                                    as units,
    CAST(SUM(f.net_revenue) / NULLIF(COUNT(DISTINCT f.order_id), 0) AS DECIMAL(18,2))  as avg_order_value,
    CAST(AVG(f.customer_rating) AS DECIMAL(3,2))                                       as avg_rating
from {{ ref('fct_orders') }} f
join {{ ref('dim_category') }} d_category on d_category.category_key = f.category_key
join {{ ref('dim_region') }} d_region on d_region.region_key = f.region_key
group by 1, 2
order by revenue DESC
