-- GENERATED by engine/render.py from stack.yaml. Do not edit; edit stack.yaml.
{{ config(materialized='table') }}

-- Revenue and delivery experience per payment method.
-- Grain: payment_method

select
    f.payment_method                                                                   as payment_method,
    SUM(f.net_revenue)                                                                 as revenue,
    COUNT(DISTINCT f.order_id)                                                         as orders,
    CAST(SUM(f.net_revenue) / NULLIF(COUNT(DISTINCT f.order_id), 0) AS DECIMAL(18,2))  as avg_order_value,
    CAST(AVG(f.discount) * 100 AS DECIMAL(5,2))                                        as avg_discount_pct,
    CAST(AVG(f.customer_rating) AS DECIMAL(3,2))                                       as avg_rating,
    CAST(AVG(f.delivery_days) AS DECIMAL(4,1))                                         as avg_delivery_days
from {{ ref('fct_orders') }} f
group by 1
order by revenue DESC
