-- GENERATED by engine/render.py from stack.yaml. Do not edit; edit stack.yaml.
{{ config(materialized='table') }}

-- Per-customer lifetime value and activity window.
-- Grain: customer_id

select
    d_customer.customer_key                                                            as customer_id,
    SUM(f.net_revenue)                                                                 as revenue,
    COUNT(DISTINCT f.order_id)                                                         as orders,
    SUM(f.quantity)                                                                    as units,
    CAST(SUM(f.net_revenue) / NULLIF(COUNT(DISTINCT f.order_id), 0) AS DECIMAL(18,2))  as avg_order_value,
    CAST(AVG(f.customer_rating) AS DECIMAL(3,2))                                       as avg_rating,
    MIN(f.order_date)                                                                  as first_order_date,
    MAX(f.order_date)                                                                  as last_order_date,
    MAX(f.order_date) - MIN(f.order_date)                                              as active_days
from {{ ref('fct_orders') }} f
join {{ ref('dim_customer') }} d_customer on d_customer.customer_key = f.customer_key
group by 1
order by revenue DESC
