-- GENERATED by engine/render.py from stack.yaml. Do not edit; edit stack.yaml.
{{ config(materialized='table') }}

-- Per-customer lifetime value and activity window.
-- Grain: customer_id

select
    customer_id                                                       as customer_id,
    SUM(net_revenue)                                                  as revenue,
    COUNT(DISTINCT order_id)                                          as orders,
    SUM(quantity)                                                     as units,
    ROUND(SUM(net_revenue) / NULLIF(COUNT(DISTINCT order_id), 0), 2)  as avg_order_value,
    ROUND(AVG(customer_rating), 2)                                    as avg_rating,
    MIN(order_date)                                                   as first_order_date,
    MAX(order_date)                                                   as last_order_date,
    MAX(order_date) - MIN(order_date)                                 as active_days
from {{ ref('stg_sales_orders') }}
group by 1
order by revenue DESC
