-- GENERATED by engine/render.py from stack.yaml. Do not edit; edit stack.yaml.
{{ config(materialized='table') }}

-- Category by region cross-tab — where each category actually sells.
-- Grain: product_category, region

select
    product_category                                                  as product_category,
    region                                                            as region,
    SUM(net_revenue)                                                  as revenue,
    COUNT(DISTINCT order_id)                                          as orders,
    SUM(quantity)                                                     as units,
    ROUND(SUM(net_revenue) / NULLIF(COUNT(DISTINCT order_id), 0), 2)  as avg_order_value,
    ROUND(AVG(customer_rating), 2)                                    as avg_rating
from {{ ref('stg_sales_orders') }}
group by 1, 2
order by revenue DESC
