-- GENERATED by engine/render.py from stack.yaml. Do not edit; edit stack.yaml.
{{ config(materialized='table') }}

-- Monthly revenue trend across the whole dataset.
-- Grain: order_month

select
    order_month                                                       as order_month,
    SUM(net_revenue)                                                  as revenue,
    SUM(gross_revenue)                                                as gross_revenue,
    SUM(discount_amount)                                              as discount_amount,
    COUNT(DISTINCT order_id)                                          as orders,
    SUM(quantity)                                                     as units,
    ROUND(SUM(net_revenue) / NULLIF(COUNT(DISTINCT order_id), 0), 2)  as avg_order_value
from {{ ref('stg_sales_orders') }}
group by 1
order by order_month
