#!/usr/bin/env python3
"""The engine: compile the metrics and marts in stack.yaml into dbt models.

Marts are the only generated artefact, because marts are the only thing that
repeats. A grain plus a list of metrics becomes a dbt model that joins the star
correctly and documents every column with the metric's own definition:

    transform/models/marts/<mart>.sql   one model per declared mart
    transform/models/marts/_marts.yml   descriptions carrying the metric SQL

Everything else in this project is hand-written and committed: the raw DDL and
grants under sql/, the staging view and the star schema under
transform/models/. Generating those cost more than it saved.

Never edit the files this writes — change stack.yaml and re-run `make render`.
"""

from __future__ import annotations

import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
MARTS = ROOT / "transform/models/marts"
BANNER = "-- GENERATED by engine/render.py from stack.yaml. Do not edit; edit stack.yaml."
YAML_BANNER = "# GENERATED by engine/render.py from stack.yaml. Do not edit; edit stack.yaml."


def write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content.rstrip() + "\n", encoding="utf-8")
    print(f"  rendered {path.relative_to(ROOT)}")


def resolve(cfg: dict, mart: dict) -> tuple[list[tuple[str, str]], list[str]]:
    """Turn a mart's dimension names into select expressions and the joins they need.

    A dimension declared with a `model` lives in a dimension table and needs a
    join; one declared with only a `column` is degenerate and comes straight off
    the fact. Each dimension model is joined at most once, however many of its
    columns a mart asks for.
    """
    star = {d["name"]: d for d in cfg["star"]["dimensions"]}
    selects: list[tuple[str, str]] = []
    joins: list[str] = []
    joined: set[str] = set()

    for name in mart["dimensions"]:
        try:
            dim = star[name]
        except KeyError:
            raise SystemExit(
                f"stack.yaml: mart '{mart['name']}' uses undeclared dimension '{name}'"
            ) from None

        if "model" not in dim:  # degenerate — on the fact table
            selects.append((f"f.{dim['column']}", name))
            continue

        alias = dim["model"].replace("dim_", "d_")
        if dim["model"] not in joined:
            joined.add(dim["model"])
            joins.append(
                f"join {{{{ ref('{dim['model']}') }}}} {alias}"
                f" on {alias}.{dim['key']} = f.{dim['key']}"
            )
        selects.append((f"{alias}.{dim['column']}", name))

    return selects, joins


def render_mart_sql(cfg: dict, mart: dict) -> str:
    metrics = {m["name"]: m for m in cfg["metrics"]}
    selects, joins = resolve(cfg, mart)
    chosen = [metrics[n] for n in mart["metrics"]] + mart.get("extra_metrics", [])

    width = max([len(m["expr"]) for m in chosen] + [len(e) for e, _ in selects])
    parts = [f"    {expr:<{width}}  as {alias}" for expr, alias in selects]
    parts += [f"    {m['expr']:<{width}}  as {m['name']}" for m in chosen]

    join_sql = ("\n" + "\n".join(joins)) if joins else ""
    group_by = ", ".join(str(i + 1) for i in range(len(selects)))
    order_by = f"\norder by {mart['order_by']}" if mart.get("order_by") else ""

    return f"""{BANNER}
{{{{ config(materialized='table') }}}}

-- {mart['description']}
-- Grain: {', '.join(mart['dimensions'])}

select
{(',' + chr(10)).join(parts)}
from {{{{ ref('{cfg['star']['fact']}') }}}} f{join_sql}
group by {group_by}{order_by}
"""


def render_marts_yml(cfg: dict) -> str:
    metrics = {m["name"]: m for m in cfg["metrics"]}
    blocks = []
    for mart in cfg["marts"]:
        cols = []
        for i, dim in enumerate(mart["dimensions"]):
            tests = "\n        data_tests: [not_null]" if i == 0 else ""
            cols.append(f'      - name: {dim}\n        description: "Grain: {dim}"{tests}')
        described = [metrics[n] for n in mart["metrics"]] + mart.get("extra_metrics", [])
        for m in described:
            cols.append(
                f'      - name: {m["name"]}\n'
                f'        description: "{m.get("description", "")} ({m["expr"]})"'
            )
        blocks.append(
            f'  - name: {mart["name"]}\n'
            f'    description: "{mart["description"]}"\n'
            f"    columns:\n" + "\n".join(cols)
        )
    return f"""{YAML_BANNER}
version: 2

models:
{chr(10).join(blocks)}
"""


def main() -> int:
    cfg = yaml.safe_load((ROOT / "stack.yaml").read_text(encoding="utf-8"))

    for stale in MARTS.glob("*.sql"):
        stale.unlink()
    for mart in cfg["marts"]:
        write(MARTS / f"{mart['name']}.sql", render_mart_sql(cfg, mart))
    write(MARTS / "_marts.yml", render_marts_yml(cfg))

    print(f"engine: {len(cfg['marts'])} marts from {len(cfg['metrics'])} metrics")
    return 0


if __name__ == "__main__":
    sys.exit(main())
