#!/usr/bin/env python3
"""The engine: compile stack.yaml into the declarative code that runs the stack.

Reads one config file and writes:

    build/01_raw_schema.sql          raw schema + table DDL
    build/02_grants.sql              read access for the MCP user
    build/03_verify.sql              post-build assertions
    transform/models/staging/*       dbt sources + the staging view
    transform/models/marts/*         one dbt model per declared mart
    serve/questions.md               the natural-language questions, versioned

Nothing here contains business logic. If a mart is wrong, fix stack.yaml and
re-run — never edit the generated files.
"""

from __future__ import annotations

import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
BANNER = "-- GENERATED by engine/render.py from stack.yaml. Do not edit; edit stack.yaml."
YAML_BANNER = "# GENERATED by engine/render.py from stack.yaml. Do not edit; edit stack.yaml."


def write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content.rstrip() + "\n", encoding="utf-8")
    print(f"  rendered {path.relative_to(ROOT)}")


def indent(text: str, spaces: int) -> str:
    pad = " " * spaces
    return "\n".join(pad + line if line else line for line in text.split("\n"))


# --------------------------------------------------------------------------
# build/*.sql — everything that runs before and after dbt
# --------------------------------------------------------------------------
def render_raw_schema(cfg: dict) -> str:
    src = cfg["source"]
    width = max(len(c["name"]) for c in src["columns"])
    cols = ",\n".join(
        f"    {c['name'].upper():<{width}}  {c['type']}" for c in src["columns"]
    )
    comments = "\n".join(
        f"COMMENT ON COLUMN {src['schema']}.{src['table']}.{c['name'].upper()} "
        f"IS '{c['description'].replace(chr(39), chr(39) * 2)}';"
        for c in src["columns"]
        if c.get("description")
    )
    return f"""{BANNER}
-- Raw landing zone for: {src['description']}

CREATE SCHEMA IF NOT EXISTS {src['schema']};

CREATE OR REPLACE TABLE {src['schema']}.{src['table']} (
{cols}
);

COMMENT ON TABLE {src['schema']}.{src['table']} IS '{src['description'].replace("'", "''")}';
{comments}
"""


def render_grants(cfg: dict) -> str:
    reader = cfg["serve"]["reader"]
    schemas = [cfg["source"]["schema"], cfg["runtime"]["model_schema"]]
    lines = "\n".join(f"GRANT SELECT ON SCHEMA {s} TO {reader};" for s in schemas)
    return f"""{BANNER}
-- Security as code: the AI reads, and can never write.

{lines}
"""


def render_verify(cfg: dict) -> str:
    """One result set: every check, its number, and PASS/FAIL."""
    src, model_schema = cfg["source"], cfg["runtime"]["model_schema"]
    raw = f"{src['schema']}.{src['table']}"
    staging = f"{model_schema}.{cfg['staging']['model'].upper()}"

    checks = [
        ("raw rows loaded", f"SELECT COUNT(*) FROM {raw}", "> 0"),
        (
            "staging = raw (no rows lost)",
            f"SELECT (SELECT COUNT(*) FROM {staging}) - (SELECT COUNT(*) FROM {raw})",
            "= 0",
        ),
        (
            "mart revenue = staging revenue",
            f"SELECT ROUND((SELECT SUM(revenue) FROM {model_schema}.MART_REVENUE_BY_CATEGORY)"
            f" - (SELECT SUM(net_revenue) FROM {staging}), 2)",
            "= 0",
        ),
    ]
    check_sql = "\nUNION ALL\n".join(
        f"SELECT '{label}' AS CHECK_NAME, ({sql}) AS ACTUAL, '{expect}' AS EXPECTED,"
        f" CASE WHEN ({sql}) {expect} THEN 'PASS' ELSE 'FAIL' END AS STATUS"
        for label, sql, expect in checks
    )
    marts = "\nUNION ALL\n".join(
        f"SELECT '{m['name'].upper()}' AS MART, COUNT(*) AS ROW_COUNT"
        f" FROM {model_schema}.{m['name'].upper()}"
        for m in cfg["marts"]
    )
    return f"""{BANNER}
-- Cheap assertions. If these look wrong, the stack is wrong.

{check_sql}
ORDER BY 1;

{marts}
ORDER BY 1;
"""


# --------------------------------------------------------------------------
# dbt models
# --------------------------------------------------------------------------
def render_sources_yml(cfg: dict) -> str:
    src = cfg["source"]
    cols = "\n".join(
        f"          - name: {c['name']}\n"
        f"            description: \"{c.get('description', '')}\""
        for c in src["columns"]
    )
    return f"""{YAML_BANNER}
version: 2

sources:
  - name: raw
    schema: {src['schema']}
    description: "{src['description']}"
    tables:
      - name: {src['table'].lower()}
        identifier: {src['table']}
        description: "Loaded verbatim from {src['file']}"
        columns:
{cols}
"""


def render_staging_sql(cfg: dict) -> str:
    st, src = cfg["staging"], cfg["source"]
    parts = [f"    {c}" for c in st["passthrough"]]
    width = max(len(d["expr"]) for d in st["derived"])
    parts += [f"    {d['expr']:<{width}}  as {d['name']}" for d in st["derived"]]
    select = ",\n".join(parts)
    return f"""{BANNER}
{{{{ config(materialized='{st['materialized']}') }}}}

-- {st['description']}

select
{select}
from {{{{ source('raw', '{src['table'].lower()}') }}}}
"""


def render_staging_yml(cfg: dict) -> str:
    st = cfg["staging"]
    src_desc = {c["name"]: c.get("description", "") for c in cfg["source"]["columns"]}
    key = st["passthrough"][0]
    lines = []
    for name in st["passthrough"]:
        # The first passthrough column is the declared grain — assert it.
        tests = "\n        data_tests: [unique, not_null]" if name == key else ""
        lines.append(
            f'      - name: {name}\n        description: "{src_desc.get(name, "")}"{tests}'
        )
    for d in st["derived"]:
        lines.append(
            f'      - name: {d["name"]}\n        description: "{d.get("description", "")}"'
        )
    body = "\n".join(lines)
    return f"""{YAML_BANNER}
version: 2

models:
  - name: {st['model']}
    description: "{st['description']}"
    columns:
{body}
"""


def render_mart_sql(cfg: dict, mart: dict) -> str:
    metrics = {m["name"]: m for m in cfg["metrics"]}
    staging = cfg["staging"]["model"]
    selected = [metrics[n] for n in mart["metrics"]] + mart.get("extra_metrics", [])
    width = max([len(m["expr"]) for m in selected] + [len(d) for d in mart["dimensions"]])
    parts = [f"    {d:<{width}}  as {d}" for d in mart["dimensions"]]
    parts += [f"    {m['expr']:<{width}}  as {m['name']}" for m in selected]
    select = ",\n".join(parts)
    group_by = ", ".join(str(i + 1) for i in range(len(mart["dimensions"])))
    order_by = mart.get("order_by")
    order_sql = f"\norder by {order_by}" if order_by else ""
    return f"""{BANNER}
{{{{ config(materialized='table') }}}}

-- {mart['description']}
-- Grain: {', '.join(mart['dimensions'])}

select
{select}
from {{{{ ref('{staging}') }}}}
group by {group_by}{order_sql}
"""


def render_marts_yml(cfg: dict) -> str:
    metrics = {m["name"]: m for m in cfg["metrics"]}
    blocks = []
    for mart in cfg["marts"]:
        cols = []
        for i, dim in enumerate(mart["dimensions"]):
            tests = "\n        data_tests: [not_null]" if i == 0 else ""
            cols.append(f'      - name: {dim}\n        description: "Grain: {dim}"{tests}')
        for name in mart["metrics"]:
            cols.append(
                f'      - name: {name}\n'
                f'        description: "{metrics[name]["description"]} ({metrics[name]["expr"]})"'
            )
        for extra in mart.get("extra_metrics", []):
            cols.append(
                f'      - name: {extra["name"]}\n'
                f'        description: "{extra.get("description", "")} ({extra["expr"]})"'
            )
        body = "\n".join(cols)
        blocks.append(
            f'  - name: {mart["name"]}\n'
            f'    description: "{mart["description"]}"\n'
            f"    columns:\n{body}"
        )
    return f"""{YAML_BANNER}
version: 2

models:
{chr(10).join(blocks)}
"""


# --------------------------------------------------------------------------
# serve — the human/AI interface
# --------------------------------------------------------------------------
def render_questions(cfg: dict) -> str:
    schema = cfg["runtime"]["model_schema"]
    questions = "\n".join(f"{i}. {q}" for i, q in enumerate(cfg["serve"]["questions"], 1))
    marts = "\n".join(
        f"| `{schema}.{m['name'].upper()}` | {m['description']} | {', '.join(m['dimensions'])} |"
        for m in cfg["marts"]
    )
    metrics = "\n".join(
        f"| `{m['name']}` | {m['description']} | `{m['expr']}` |" for m in cfg["metrics"]
    )
    return f"""<!-- GENERATED by engine/render.py from stack.yaml. Do not edit; edit stack.yaml. -->

# Ask your data

No BI tool. Point an MCP client (Claude Code, Codex, Cursor) at the local Exasol
and ask in plain English. The marts below are what it will find.

## Questions worth starting with

{questions}

## What is in the database

| Mart | What it answers | Grain |
|---|---|---|
{marts}

Plus `{schema}.{cfg['staging']['model'].upper()}` — the typed order-level view every mart is built from.

## Metric definitions

The AI does not have to guess what "revenue" means. These are compiled into the
marts and into the dbt docs, so the definition and the number always agree.

| Metric | Meaning | SQL |
|---|---|---|
{metrics}
"""


def main() -> int:
    cfg = yaml.safe_load((ROOT / "stack.yaml").read_text(encoding="utf-8"))
    print(f"engine: compiling stack.yaml -> {cfg['project']['name']}")

    write(ROOT / "build/01_raw_schema.sql", render_raw_schema(cfg))
    write(ROOT / "build/02_grants.sql", render_grants(cfg))
    write(ROOT / "build/03_verify.sql", render_verify(cfg))

    models = ROOT / "transform/models"
    write(models / "staging/_sources.yml", render_sources_yml(cfg))
    write(models / f"staging/{cfg['staging']['model']}.sql", render_staging_sql(cfg))
    write(models / "staging/_staging.yml", render_staging_yml(cfg))

    for stale in (models / "marts").glob("*.sql"):
        stale.unlink()
    for mart in cfg["marts"]:
        write(models / f"marts/{mart['name']}.sql", render_mart_sql(cfg, mart))
    write(models / "marts/_marts.yml", render_marts_yml(cfg))

    write(ROOT / "serve/questions.md", render_questions(cfg))

    print(f"engine: {len(cfg['marts'])} marts, {len(cfg['metrics'])} metrics")
    return 0


if __name__ == "__main__":
    sys.exit(main())
