-- GENERATED by engine/render.py from stack.yaml. Do not edit; edit stack.yaml.
{{ config(materialized='view') }}

-- Typed and enriched order lines. One row per order.

select
    order_id,
    customer_id,
    product_category,
    region,
    payment_method,
    quantity,
    unit_price,
    discount,
    delivery_days,
    customer_rating,
    TO_DATE(order_date, 'MM/DD/YYYY')                                                    as order_date,
    DATE_TRUNC('month', TO_DATE(order_date, 'MM/DD/YYYY'))                               as order_month,
    EXTRACT(YEAR FROM TO_DATE(order_date, 'MM/DD/YYYY'))                                 as order_year,
    ROUND(quantity * unit_price, 2)                                                      as gross_revenue,
    revenue                                                                              as net_revenue,
    ROUND(quantity * unit_price - revenue, 2)                                            as discount_amount,
    CASE WHEN TO_DATE(order_date, 'MM/DD/YYYY') > CURRENT_DATE THEN TRUE ELSE FALSE END  as is_future_order
from {{ source('raw', 'sales_orders') }}
